//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phase5
{
    using System;
    using System.Collections.Generic;
    
    public partial class LicenseDB
    {
        public string Business_Name { get; set; }
        public string Street_Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string Business_Phone_Number { get; set; }
        public string License_Status { get; set; }
        public int FID { get; set; }
        public string Classification_Code { get; set; }
        public string Classification_Description { get; set; }
    }
}
